apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "hfs-nodes-security"
spec:
  description: "Traslado de reglas UFW a Cilium Host Firewall"
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  ingress:
    # 1. K8s API e Infraestructura
    - fromEntities:
        - cluster
        - host
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
            - port: "9345"
              protocol: TCP
            - port: "10250"
              protocol: TCP
    
    # 2. Acceso Administrativo
    - fromCIDRSet:
        - cidr: "172.16.8.208/32"
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
            - port: "22"
              protocol: TCP

    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "22"
              protocol: TCP

    # 3. Cilium Internal
    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "8472"
              protocol: UDP
            - port: "4240"
              protocol: TCP
            - port: "51871"
              protocol: UDP
            - port: "4244"
              protocol: TCP

    # 4. TRÁFICO DE ALMACENAMIENTO (CEPH INTERNAL)
    - fromEntities:
        - remote-node
      toPorts:
        - ports:
            - port: "6789"
              protocol: TCP
            - port: "3300"
              protocol: TCP
            - port: "6800"
              endPort: 7300
              protocol: TCP

    # 5. Servicios y NodePorts
    - fromEntities:
        - world
        - cluster
        - remote-node
      toPorts:
        - ports:
            - port: "30000"
              endPort: 32767
              protocol: TCP

    # 6. Bacula y Otros Servicios
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "9101"
              endPort: 9103
              protocol: TCP
            - port: "9097"
              protocol: TCP

  egress:
    # Combinación de entidades permitidas y puertos específicos para Ceph/Telemetría
    - toEntities:
        - cluster
        - world
        - host
        - remote-node
